package main

import (
	"context"
	"fmt"
	"log"
	"log/slog"
	"net/http"
	"os"
	"os/signal"
	"path/filepath"
	"syscall"

	"github.com/gin-gonic/gin"

	"github.com/suprimkhatri77/cartspace/backend/internal/config"
	"github.com/suprimkhatri77/cartspace/backend/internal/database"
	dbgen "github.com/suprimkhatri77/cartspace/backend/internal/database/generated"
	"github.com/suprimkhatri77/cartspace/backend/internal/middleware"
	"github.com/suprimkhatri77/cartspace/backend/internal/routes"
	"github.com/suprimkhatri77/cartspace/backend/internal/validator"
)

func main() {

	// loading our env vars
	cfg, err := config.Load()
	if err != nil {
		log.Fatalf("config: %v", err)
	}

	gin.SetMode(cfg.GinMode)

	if cfg.DatabaseURL == "" {
		log.Fatal("config: DATABASE_URL is required (set it in .env or environment)")
	}

	ctx := context.Background()
	db, err := database.New(ctx, cfg.DatabaseURL)
	if err != nil {
		log.Fatalf("database: %v", err)
	}

	// automatically called when the program is exited
	defer db.Close()

	queries := dbgen.New(db.Pool)

	// Path to openapi.json (generated by packages/openapi, consumed at runtime)
	openapiPath := os.Getenv("OPENAPI_PATH")
	if openapiPath == "" {
		openapiPath = filepath.Join("openapi.json")
	}

	// initializing custom validator
	validator.Init()

	var handler slog.Handler
	if os.Getenv("GO_ENV") == "production" {
		handler = slog.NewJSONHandler(os.Stdout, nil)
	} else {
		handler = slog.NewTextHandler(os.Stdout, &slog.HandlerOptions{
			Level:     slog.LevelDebug,
			AddSource: true,
		})
	}
	logger := slog.New(handler)
	slog.SetDefault(logger)

	r := gin.New()
	r.Use(middleware.Recovery())
	r.Use(gin.Logger())
	r.Use(middleware.CORS())

	routes.Setup(r, routes.Config{
		OpenAPIPath: openapiPath,
		Queries:     queries,
		Config:      cfg,
	})

	srv := &http.Server{
		Addr:    fmt.Sprintf(":%d", cfg.Port),
		Handler: r,
	}

	go func() {
		slog.Info("server listening on", "PORT", srv.Addr)
		if err := srv.ListenAndServe(); err != nil && err != http.ErrServerClosed {
			log.Fatalf("listen: %v", err)
		}
	}()

	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)
	<-quit
	log.Println("shutting down...")
	if err := srv.Shutdown(context.Background()); err != nil {
		log.Printf("server shutdown: %v", err)
	}
	log.Println("server stopped")
}
